{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "memgraphExporter.fullname" . }}-config
  namespace: {{ .Values.prometheus.namespace | default .Release.Namespace }}
  labels:
    {{- include "memgraphExporter.labels" . | nindent 4 }}
data:
  standalone_config.yaml: |
    exporter:
      port: {{ .Values.prometheus.memgraphExporter.port }}
    memgraph:
      endpoint_url: http://{{ include "memgraph.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
      port: {{ .Values.service.httpPortMonitoring }}
    general:
      pull_frequency_seconds: {{ .Values.prometheus.memgraphExporter.pullFrequencySeconds }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "memgraphExporter.fullname" . }}
  namespace: {{ .Values.prometheus.namespace | default .Release.Namespace }}
  labels:
    {{- include "memgraphExporter.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "memgraphExporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "memgraphExporter.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: exporter
          image: {{ .Values.prometheus.memgraphExporter.repository }}:{{ .Values.prometheus.memgraphExporter.tag }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/mg-exporter/standalone_config.yaml
              subPath: standalone_config.yaml
          ports:
            - containerPort: {{ .Values.prometheus.memgraphExporter.port }}
          env:
            - name: DEPLOYMENT_TYPE
              value: standalone
            - name: CONFIG_FILE
              value: /etc/mg-exporter/standalone_config.yaml
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "memgraphExporter.fullname" . }}-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "memgraphExporter.fullname" . }}
  namespace: {{ .Values.prometheus.namespace | default .Release.Namespace }}
  labels:
    {{- include "memgraphExporter.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "memgraphExporter.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      name: tcp-metrics-port
      port: {{ .Values.prometheus.memgraphExporter.port }}
      targetPort: {{ .Values.prometheus.memgraphExporter.port }}
---
{{- if .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "memgraphExporter.fullname" . }}
  namespace: {{ .Values.prometheus.namespace | default .Release.Namespace }}
  labels:
    {{- include "memgraphExporter.labels" . | nindent 4 }}
    release: {{ .Values.prometheus.serviceMonitor.kubePrometheusStackReleaseName }}
spec:
  selector:
    matchLabels:
      {{- include "memgraphExporter.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: tcp-metrics-port  # must be the same as the service port name
      interval: {{ .Values.prometheus.serviceMonitor.interval }}
  namespaceSelector:
    matchNames:
      - {{ .Values.prometheus.namespace | default .Release.Namespace }} # This refers to where our service exposing the exporter is located
{{- end }}
{{- end }}